[metadata]
  package = "github.com/zchee/ghctl"

required = []
ignored = [
  "google.golang.org/appengine/*",
  "golang.org/x/oauth2/internal/*",
]

[prune]
  go-tests = true
  unused-packages = true
  non-go = true

[[constraint]]
  name = "github.com/fatih/color"
  branch = "master"

[[constraint]]
  name = "github.com/google/go-github"
  branch = "master"

[[constraint]]
  name = "github.com/tj/go-spin"
  branch = "master"

[[constraint]]
  name = "github.com/spf13/cobra"
  branch = "master"
